// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lazjcwtrkmhcmaxnkczy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxhempjd3Rya21oY21heG5rY3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjQ2NjUsImV4cCI6MjA3MDA0MDY2NX0.4X1Haujk9cNHmPsPcHulF9W0VRfrd5SHh_i5eguzqWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});